name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # ให้สามารถ trigger manually ได้

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10  # เปลี่ยนจาก 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # เปลี่ยนจาก '3.12'
        
    - name: Install system dependencies
      run: |
        # Install any Windows-specific dependencies if needed
        echo "Installing system dependencies..."
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 PyQt6-Qt6 PyQt6-sip
        # Try to install pyiec61850, continue if fails
        pip install pyiec61850 || echo "pyiec61850 not available, continuing..."
        pip install -r requirements.txt

    - name: Verify project structure
      run: |
        echo "=== Project Structure ==="
        dir
        echo "=== Code folder ==="
        dir code
        echo "=== Spec file exists ==="
        if (Test-Path "uranus.spec") { echo "✅ uranus.spec found" } else { echo "❌ uranus.spec not found" }
        
    - name: Build executable with PyInstaller
      run: |
        echo "Starting PyInstaller build..."
        pyinstaller uranus.spec --clean
        echo "Build completed!"
        
    - name: Verify build output
      run: |
        echo "=== Dist folder contents ==="
        if (Test-Path "dist") { 
          dir dist
          if (Test-Path "dist/Uranus.exe") { 
            echo "✅ Uranus.exe created successfully!"
            $fileInfo = Get-ChildItem "dist/Uranus.exe"
            echo "File size: $($fileInfo.Length) bytes"
          } else { 
            echo "❌ Uranus.exe not found"
            echo "Available files in dist:"
            dir dist
          }
        } else { 
          echo "❌ dist folder not created" 
        }
        
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: Uranus-Windows-x64
        path: |
          dist/Uranus.exe
          dist/Uranus/
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Uranus.exe
        body: |
          🚀 **Uranus Windows Build**
          
          **Built from:** ${{ github.sha }}
          **Python Version:** 3.12
          **Platform:** Windows x64
          
          **Installation:**
          1. Download `Uranus.exe`
          2. Run directly (no installation required)
          
          **Requirements:**
          - Windows 10/11 x64
          - No Python installation required
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}